(* *)

diagram = "drakon" icon_content parameters? ( primitive | silhouette );

parameters = icon_content;

(* A primitive is used for simple diagrams *)
primitive = "primitive" "{" skewer "end"? "}";

(* A silhouette is used for an algorithm which is split up in branches *)
silhouette = "silhouette" "{" branch+ "}";
branch = "branch" identifier "{" skewer (address|end) "}";

(* *)
skewer = (action | insertion)*;

(* Skewer stuff *)
question = "question" icon_content ("yes"|"no") "{" skewer address? "}";

action = "action" icon_content;
insertion = "insertion" icon_content;

address = "address" "(" identifier ")";
end = "end";

icon_content = ("(" identifier ")") | stuff;
stuff =  "(*" anything "*)";

label = "#" identifier;
